name: env4dzh
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - altair==5.4.1 ; python_version >= "3.10" and python_version < "4.0"
    - annotated-types==0.7.0 ; python_version >= "3.10" and python_version < "4.0"
    - attrs==24.2.0 ; python_version >= "3.10" and python_version < "4.0"
    - audio-helper @ git+https://github.com/warith-harchaoui/audio-helper.git@430a86887766629c21f1660cd21ee87b4e49d15d ; python_version >= "3.10" and python_version < "4.0"
    - bcrypt==4.2.0 ; python_version >= "3.10" and python_version < "4.0"
    - blinker==1.8.2 ; python_version >= "3.10" and python_version < "4.0"
    - blis==1.0.1 ; python_version >= "3.10" and python_version < "4.0"
    - brotli==1.1.0 ; python_version >= "3.10" and python_version < "4.0" and implementation_name == "cpython"
    - brotlicffi==1.1.0.0 ; python_version >= "3.10" and python_version < "4.0" and implementation_name != "cpython"
    - build==1.2.2.post1 ; python_version >= "3.10" and python_version < "4.0"
    - cachecontrol==0.14.0 ; python_version >= "3.10" and python_version < "4.0"
    - cachecontrol[filecache]==0.14.0 ; python_version >= "3.10" and python_version < "4.0"
    - cachetools==5.5.0 ; python_version >= "3.10" and python_version < "4.0"
    - catalogue==2.0.10 ; python_version >= "3.10" and python_version < "4.0"
    - certifi==2024.8.30 ; python_version >= "3.10" and python_version < "4.0"
    - cffi==1.17.1 ; python_version >= "3.10" and python_version < "4.0"
    - charset-normalizer==3.4.0 ; python_version >= "3.10" and python_version < "4.0"
    - cleo==2.1.0 ; python_version >= "3.10" and python_version < "4.0"
    - click==8.1.7 ; python_version >= "3.10" and python_version < "4.0"
    - cloudpathlib==0.20.0 ; python_version >= "3.10" and python_version < "4.0"
    - colorama==0.4.6 ; python_version >= "3.10" and python_version < "4.0" and (platform_system == "Windows" or sys_platform == "win32" or os_name == "nt")
    - colorlog==6.8.2 ; python_version >= "3.10" and python_version < "4.0"
    - confection==0.1.5 ; python_version >= "3.10" and python_version < "4.0"
    - contourpy==1.3.0 ; python_version >= "3.10" and python_version < "4.0"
    - crashtest==0.4.1 ; python_version >= "3.10" and python_version < "4.0"
    - cryptography==43.0.3 ; python_version >= "3.10" and python_version < "4.0"
    - cycler==0.12.1 ; python_version >= "3.10" and python_version < "4.0"
    - cymem==2.0.8 ; python_version >= "3.10" and python_version < "4.0"
    - cython==3.0.11 ; python_version >= "3.10" and python_version < "4.0"
    - distlib==0.3.9 ; python_version >= "3.10" and python_version < "4.0"
    - dulwich==0.21.7 ; python_version >= "3.10" and python_version < "4.0"
    - fastjsonschema==2.20.0 ; python_version >= "3.10" and python_version < "4.0"
    - ffmpeg-python==0.2.0 ; python_version >= "3.10" and python_version < "4.0"
    - filelock==3.16.1 ; python_version >= "3.10" and python_version < "4.0"
    - fonttools==4.54.1 ; python_version >= "3.10" and python_version < "4.0"
    - fsspec==2024.10.0 ; python_version >= "3.10" and python_version < "4.0"
    - future==1.0.0 ; python_version >= "3.10" and python_version < "4.0"
    - gitdb==4.0.11 ; python_version >= "3.10" and python_version < "4.0"
    - gitpython==3.1.43 ; python_version >= "3.10" and python_version < "4.0"
    - huggingface-hub==0.26.1 ; python_version >= "3.10" and python_version < "4.0"
    - idna==3.10 ; python_version >= "3.10" and python_version < "4.0"
    - importlib-metadata==8.5.0 ; python_version >= "3.10" and python_version < "4.0"
    - installer==0.7.0 ; python_version >= "3.10" and python_version < "4.0"
    - jaraco-classes==3.4.0 ; python_version >= "3.10" and python_version < "4.0"
    - jeepney==0.8.0 ; python_version >= "3.10" and python_version < "4.0" and sys_platform == "linux"
    - jinja2==3.1.4 ; python_version >= "3.10" and python_version < "4.0"
    - joblib==1.4.2 ; python_version >= "3.10" and python_version < "4.0"
    - jsonschema-specifications==2024.10.1 ; python_version >= "3.10" and python_version < "4.0"
    - jsonschema==4.23.0 ; python_version >= "3.10" and python_version < "4.0"
    - keybert==0.8.5 ; python_version >= "3.10" and python_version < "4.0"
    - keyring==24.3.1 ; python_version >= "3.10" and python_version < "4.0"
    - kiwisolver==1.4.7 ; python_version >= "3.10" and python_version < "4.0"
    - langcodes==3.4.1 ; python_version >= "3.10" and python_version < "4.0"
    - langdetect==1.0.9 ; python_version >= "3.10" and python_version < "4.0"
    - language-data==1.2.0 ; python_version >= "3.10" and python_version < "4.0"
    - marisa-trie==1.2.1 ; python_version >= "3.10" and python_version < "4.0"
    - markdown-it-py==3.0.0 ; python_version >= "3.10" and python_version < "4.0"
    - markupsafe==3.0.2 ; python_version >= "3.10" and python_version < "4.0"
    - matplotlib==3.9.2 ; python_version >= "3.10" and python_version < "4.0"
    - mdurl==0.1.2 ; python_version >= "3.10" and python_version < "4.0"
    - more-itertools==10.5.0 ; python_version >= "3.10" and python_version < "4.0"
    - mpmath==1.3.0 ; python_version >= "3.10" and python_version < "4.0"
    - msgpack==1.1.0 ; python_version >= "3.10" and python_version < "4.0"
    - murmurhash==1.0.10 ; python_version >= "3.10" and python_version < "4.0"
    - mutagen==1.47.0 ; python_version >= "3.10" and python_version < "4.0"
    - narwhals==1.11.1 ; python_version >= "3.10" and python_version < "4.0"
    - networkx==3.4.2 ; python_version >= "3.10" and python_version < "4.0"
    - nltk==3.9.1 ; python_version >= "3.10" and python_version < "4.0"
    - numpy==2.0.2 ; python_version >= "3.10" and python_version < "4.0"
    - nvidia-cublas-cu12==12.4.5.8 ; platform_system == "Linux" and platform_machine == "x86_64" and python_version >= "3.10" and python_version < "4.0"
    - nvidia-cuda-cupti-cu12==12.4.127 ; platform_system == "Linux" and platform_machine == "x86_64" and python_version >= "3.10" and python_version < "4.0"
    - nvidia-cuda-nvrtc-cu12==12.4.127 ; platform_system == "Linux" and platform_machine == "x86_64" and python_version >= "3.10" and python_version < "4.0"
    - nvidia-cuda-runtime-cu12==12.4.127 ; platform_system == "Linux" and platform_machine == "x86_64" and python_version >= "3.10" and python_version < "4.0"
    - nvidia-cudnn-cu12==9.1.0.70 ; platform_system == "Linux" and platform_machine == "x86_64" and python_version >= "3.10" and python_version < "4.0"
    - nvidia-cufft-cu12==11.2.1.3 ; platform_system == "Linux" and platform_machine == "x86_64" and python_version >= "3.10" and python_version < "4.0"
    - nvidia-curand-cu12==10.3.5.147 ; platform_system == "Linux" and platform_machine == "x86_64" and python_version >= "3.10" and python_version < "4.0"
    - nvidia-cusolver-cu12==11.6.1.9 ; platform_system == "Linux" and platform_machine == "x86_64" and python_version >= "3.10" and python_version < "4.0"
    - nvidia-cusparse-cu12==12.3.1.170 ; platform_system == "Linux" and platform_machine == "x86_64" and python_version >= "3.10" and python_version < "4.0"
    - nvidia-nccl-cu12==2.21.5 ; platform_system == "Linux" and platform_machine == "x86_64" and python_version >= "3.10" and python_version < "4.0"
    - nvidia-nvjitlink-cu12==12.4.127 ; platform_system == "Linux" and platform_machine == "x86_64" and python_version >= "3.10" and python_version < "4.0"
    - nvidia-nvtx-cu12==12.4.127 ; platform_system == "Linux" and platform_machine == "x86_64" and python_version >= "3.10" and python_version < "4.0"
    - opencv-python==4.10.0.84 ; python_version >= "3.10" and python_version < "4.0"
    - os-helper @ git+https://github.com/warith-harchaoui/os-helper.git@bc44b9b19e52200a40fe4b1f0282926959769878 ; python_version >= "3.10" and python_version < "4.0"
    - packaging==24.1 ; python_version >= "3.10" and python_version < "4.0"
    - pandas==2.2.3 ; python_version >= "3.10" and python_version < "4.0"
    - paramiko==3.5.0 ; python_version >= "3.10" and python_version < "4.0"
    - pexpect==4.9.0 ; python_version >= "3.10" and python_version < "4.0"
    - pillow==10.4.0 ; python_version >= "3.10" and python_version < "4.0"
    - pkginfo==1.11.2 ; python_version >= "3.10" and python_version < "4.0"
    - platformdirs==4.3.6 ; python_version >= "3.10" and python_version < "4.0"
    - poetry-core==1.9.1 ; python_version >= "3.10" and python_version < "4.0"
    - poetry-plugin-export==1.8.0 ; python_version >= "3.10" and python_version < "4.0"
    - poetry2setup==1.1.0 ; python_version >= "3.10" and python_version < "4.0"
    - poetry==1.8.4 ; python_version >= "3.10" and python_version < "4.0"
    - preshed==3.0.9 ; python_version >= "3.10" and python_version < "4.0"
    - protobuf==5.28.3 ; python_version >= "3.10" and python_version < "4.0"
    - ptyprocess==0.7.0 ; python_version >= "3.10" and python_version < "4.0"
    - pyarrow==18.0.0 ; python_version >= "3.10" and python_version < "4.0"
    - pycparser==2.22 ; python_version >= "3.10" and python_version < "4.0"
    - pycryptodomex==3.21.0 ; python_version >= "3.10" and python_version < "4.0"
    - pydantic-core==2.23.4 ; python_version >= "3.10" and python_version < "4.0"
    - pydantic==2.9.2 ; python_version >= "3.10" and python_version < "4.0"
    - pydeck==0.9.1 ; python_version >= "3.10" and python_version < "4.0"
    - pygments==2.18.0 ; python_version >= "3.10" and python_version < "4.0"
    - pynacl==1.5.0 ; python_version >= "3.10" and python_version < "4.0"
    - pyparsing==3.2.0 ; python_version >= "3.10" and python_version < "4.0"
    - pyproject-hooks==1.2.0 ; python_version >= "3.10" and python_version < "4.0"
    - pysftp==0.2.9 ; python_version >= "3.10" and python_version < "4.0"
    - python-dateutil==2.9.0.post0 ; python_version >= "3.10" and python_version < "4.0"
    - python-dotenv==1.0.1 ; python_version >= "3.10" and python_version < "4.0"
    - pytz==2024.2 ; python_version >= "3.10" and python_version < "4.0"
    - pywin32-ctypes==0.2.3 ; python_version >= "3.10" and python_version < "4.0" and sys_platform == "win32"
    - pyyaml==6.0.2 ; python_version >= "3.10" and python_version < "4.0"
    - rake-nltk==1.0.6 ; python_version >= "3.10" and python_version < "4.0"
    - rapidfuzz==3.10.1 ; python_version >= "3.10" and python_version < "4.0"
    - referencing==0.35.1 ; python_version >= "3.10" and python_version < "4.0"
    - regex==2024.9.11 ; python_version >= "3.10" and python_version < "4.0"
    - requests-toolbelt==1.0.0 ; python_version >= "3.10" and python_version < "4.0"
    - requests==2.32.3 ; python_version >= "3.10" and python_version < "4.0"
    - rich==13.9.3 ; python_version >= "3.10" and python_version < "4.0"
    - rpds-py==0.20.0 ; python_version >= "3.10" and python_version < "4.0"
    - safetensors==0.4.5 ; python_version >= "3.10" and python_version < "4.0"
    - scikit-learn==1.5.2 ; python_version >= "3.10" and python_version < "4.0"
    - scipy==1.14.1 ; python_version >= "3.10" and python_version < "4.0"
    - secretstorage==3.3.3 ; python_version >= "3.10" and python_version < "4.0" and sys_platform == "linux"
    - sentence-transformers==3.2.1 ; python_version >= "3.10" and python_version < "4.0"
    - setuptools==75.2.0 ; python_version >= "3.10" and python_version < "4.0"
    - sftp-helper @ git+https://github.com/warith-harchaoui/sftp-helper.git@5a10aeb06237ed6381137270b7b38719c65fdd47 ; python_version >= "3.10" and python_version < "4.0"
    - shellingham==1.5.4 ; python_version >= "3.10" and python_version < "4.0"
    - six==1.16.0 ; python_version >= "3.10" and python_version < "4.0"
    - smart-open==7.0.5 ; python_version >= "3.10" and python_version < "4.0"
    - smmap==5.0.1 ; python_version >= "3.10" and python_version < "4.0"
    - soundfile==0.12.1 ; python_version >= "3.10" and python_version < "4.0"
    - spacy-legacy==3.0.12 ; python_version >= "3.10" and python_version < "4.0"
    - spacy-loggers==1.0.5 ; python_version >= "3.10" and python_version < "4.0"
    - spacy==3.8.2 ; python_version >= "3.10" and python_version < "4.0"
    - srsly==2.4.8 ; python_version >= "3.10" and python_version < "4.0"
    - streamlit==1.39.0 ; python_version >= "3.10" and python_version < "4.0"
    - sympy==1.13.1 ; python_version >= "3.10" and python_version < "4.0"
    - tenacity==9.0.0 ; python_version >= "3.10" and python_version < "4.0"
    - thinc==8.3.2 ; python_version >= "3.10" and python_version < "4.0"
    - threadpoolctl==3.5.0 ; python_version >= "3.10" and python_version < "4.0"
    - tokenizers==0.20.1 ; python_version >= "3.10" and python_version < "4.0"
    - toml==0.10.2 ; python_version >= "3.10" and python_version < "4.0"
    - tomli==2.0.2 ; python_version >= "3.10" and python_version < "4.0"
    - tomlkit==0.13.2 ; python_version >= "3.10" and python_version < "4.0"
    - torch==2.5.0 ; python_version >= "3.10" and python_version < "4.0"
    - torchaudio==2.5.0 ; python_version >= "3.10" and python_version < "4.0"
    - tornado==6.4.1 ; python_version >= "3.10" and python_version < "4.0"
    - tqdm==4.66.6 ; python_version >= "3.10" and python_version < "4.0"
    - transformers==4.46.0 ; python_version >= "3.10" and python_version < "4.0"
    - triton==3.1.0 ; platform_system == "Linux" and platform_machine == "x86_64" and python_version < "3.13" and python_version >= "3.10"
    - trove-classifiers==2024.10.21.16 ; python_version >= "3.10" and python_version < "4.0"
    - typer==0.12.5 ; python_version >= "3.10" and python_version < "4.0"
    - typing-extensions==4.12.2 ; python_version >= "3.10" and python_version < "4.0"
    - tzdata==2024.2 ; python_version >= "3.10" and python_version < "4.0"
    - urllib3==2.2.3 ; python_version >= "3.10" and python_version < "4.0"
    - validators==0.34.0 ; python_version >= "3.10" and python_version < "4.0"
    - video-helper @ git+https://github.com/warith-harchaoui/video-helper.git@19bbd78b1f89883b150855d2f5336e5171f4d8d2 ; python_version >= "3.10" and python_version < "4.0"
    - vidgear==0.3.3 ; python_version >= "3.10" and python_version < "4.0"
    - virtualenv==20.27.0 ; python_version >= "3.10" and python_version < "4.0"
    - wasabi==1.1.3 ; python_version >= "3.10" and python_version < "4.0"
    - watchdog==5.0.3 ; python_version >= "3.10" and python_version < "4.0" and platform_system != "Darwin"
    - weasel==0.4.1 ; python_version >= "3.10" and python_version < "4.0"
    - websockets==13.1 ; python_version >= "3.10" and python_version < "4.0"
    - wrapt==1.16.0 ; python_version >= "3.10" and python_version < "4.0"
    - xattr==1.1.0 ; python_version >= "3.10" and python_version < "4.0"
    - yt-dlp==2024.10.22 ; python_version >= "3.10" and python_version < "4.0"
    - yt-helper @ git+https://github.com/warith-harchaoui/yt-helper.git@4128816d896dfd356c40bcbd5680ab85d25c6949 ; python_version >= "3.10" and python_version < "4.0"
    - zipp==3.20.2 ; python_version >= "3.10" and python_version < "4.0"
